version: '3'

services:
  henskens-service:
    build:
      context: ./backEnd/henskens-service
      dockerfile: Dockerfile
    container_name: henskens-service
    ports:
      - "8080:8080"

  api-gateway:
    depends_on:
      - henskens-service
    image: peterhenskens/api-gateway:latest
    build:
      context: ./backEnd/api-gateway
      dockerfile: Dockerfile
    ports:
      - "8083:8083"
    links:
      - henskens-service
    environment:
      PRODUCT_SERVICE_BASEURL: henskens-service:8080
      USER_SERVICE_BASEURL: henskens-service:8080

  db1:
    image: couchbase
    container_name: db1
    hostname: db1
    networks:
      - couchbase-net
    ports:
      - "8091:8091"
      - "8092:8092"
      - "8093:8093"
      - "8094:8094"
      - "11210:11210"
    environment:
      - SERVICES=data;index;query;fts
      - CB_REST_USERNAME=Administrator
      - CB_REST_PASSWORD=g9VNheVwrF@!3wS
    volumes:
      - couchbase-data:/opt/couchbase/var

networks:
  couchbase-net:

volumes:
  couchbase-data:
