services:
 mongo-products:
  image: mongo:latest
  ports:
    - 27017:27017
  volumes:
    - mongodb_product_data:/data/db
    
 mysql-user:
  image: mysql:latest
  ports:
    - 3306:3306
  volumes:
    - mysql_user_data:/var/lib/mysql
  environment:
   MYSQL_ROOT_PASSWORD: abc123
    
 mysql-portfolio:
  image: mysql:latest
  ports:
    - 3307:3306
  volumes:
    - mysql_portfolio_data:/var/lib/mysql
  environment:
   MYSQL_ROOT_PASSWORD: abc123
    
 product-service:
  depends_on:
    - mongo-products
  image: peterhenskens/product-service:latest
  build:
    context: ./backEnd/product-service
    dockerfile: Dockerfile
  ports:
    - 8080:8080
  links:
    - mongo-products
  environment:
   MONGODB_PORT: 27017
   MONGODB_HOST: mongo-products
   
 portfolio-service:
  depends_on:
    - mysql-portfolio
  image: peterhenskens/portfolio-service:latest
  build:
    context: ./backEnd/portfolio-service
    dockerfile: Dockerfile
  ports:
    - 8082:8082
  links:
    - mysql-portfolio
  environment:
   MYSQL_DB_USERNAME: root
   MYSQL_DB_PASSWORD: abc123
   MYSQL_DB_HOST: mysql-portfolio
   MYSQL_DB_PORT: 3307

 user-service:
  depends_on:
    - product-service
    - portfolio-service
  image: peterhenskens/user-service:latest
  build:
    context: ./backEnd/user-service
    dockerfile: Dockerfile
  ports:
    - 8081:8081
  links:
    - product-service
    - portfolio-service
  environment:
   PRODUCT_SERVICE_BASEURL: product-service:8080
   portfolio_INFO_SERVICE_BASEURL: portfolio-service:8082
   MYSQL_DB_USERNAME: root
   MYSQL_DB_PASSWORD: abc123
   MYSQL_DB_HOST: mysql-user
   MYSQL_DB_PORT: 3306

 api-gateway:
   depends_on:
     - product-service
     - user-service
   image: peterhenskens/api-gateway:latest
   build:
    context: ./backEnd/api-gateway
    dockerfile: Dockerfile
   ports:
     - 8083:8083
   links:
     - product-service
     - user-service
   environment:
     PRODUCT_SERVICE_BASEURL: product-service:8080
     user_SERVICE_BASEURL: user-service:8081

volumes:
 mongodb_product_data:
 mysql_portfolio_data:
 mysql_user_data: