version: '3'

services:
  henskens-service:
    build:
      context: ./backEnd/henskens-service
    ports:
      - "8080:8080"
    depends_on:
      - couchbase

  portfolio-service:
    build:
      context: ./backEnd/portfolio-service
    ports:
      - "8081:8081"
    depends_on:
      - mongodb

  api-gateway:
    build:
      context: ./backEnd/api-gateway
    ports:
      - "8765:8765"
    depends_on:
      - henskens-service
      - portfolio-service

  couchbase:
    image: couchbase
    ports:
      - "8091:8091"
      - "8092:8092"
      - "8093:8093"
      - "8094:8094"
      - "11210:11210"
    environment:
      COUCHBASE_ROOT_PASSWORD: g9VNheVwrF@!3wS
      COUCHBASE_BUCKET: portfolio
      COUCHBASE_BUCKET_PASSWORD: g9VNheVwrF@!3wS
    volumes:
      - couchbase-data:/opt/couchbase/var

  mongodb:
    image: mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: administrator
      MONGO_INITDB_ROOT_PASSWORD: g9VNheVwrF3wS
    volumes:
      - mongodb-data:/data/db

volumes:
  couchbase-data:
  mongodb-data:
