server:
  port: 8083

logging:
  level:
    root: INFO
    org.springframework.cloud.gateway: TRACE
    org.springframework.cloud.gateway.route.RouteDefinitionRouteLocator: INFO
    reactor.netty: TRACE

spring:
  cloud:
    gateway:
      routes:
        - id: henskens-service
          uri: http://${PRODUCT_SERVICE_BASEURL:localhost:8080}
          predicates:
            - Path=/henskens
            - Method=POST
          filters:
            - SetPath=/api/henskens