server:
  port: 8083

logging:
  level:
    root: INFO
    org.springframework.cloud.gateway: TRACE
    org.springframework.cloud.gateway.route.RouteDefinitionRouteLocator: INFO
    reactor.netty: TRACE

spring:
  cloud:
    gateway:
      routes:
        - id: product-service
          uri: http://${PRODUCT_SERVICE_BASEURL:localhost:8080}
          predicates:
            - Path=/products
            - Method=POST
          filters:
            - SetPath=/api/product
        - id: portfolio-service
          uri: http://${PORTFOLIO_SERVICE_BASEURL:localhost:8080}
          predicates:
            - Path=/portfolios
            - Method=GET
          filters:
            - SetPath=/api/portfolio
        - id: user-service
          uri: http://${USER_SERVICE_BASEURL:localhost:8081}
          predicates:
            - Path=/users
          filters:
            - SetPath=/api/user